version: "3.8"

services:
  qinglong:
    image: whyour/qinglong:latest
    container_name: qinglong
    volumes:
      - /project/sandbox/ql/data:/ql/data
    ports:
      - "5700:5700"
    environment:
      QlBaseUrl: "/"
    restart: always

  alist:
    image: "ykxvk8yl5l/alist:latest"
    container_name: alist
    restart: always
    volumes:
      - "/project/sandbox/alist:/opt/alist/data"
    ports:
      - "5244:5244"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - ALIST_ADMIN_PASSWORD=admin

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    volumes:
      - /project/sandbox/uptimekuma:/app/data
    ports:
      - "3001:3001" # <Host Port>:<Container Port>

 db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - "/project/sandbox/db:/var/lib/mysql"   
    environment:
      - "TZ=Asia/Shanghai"
      - "MYSQL_ROOT_PASSWORD=jiehdo!25165n"
      - "MYSQL_DATABASE=kodbox"
      - "MYSQL_USER=bodbox"
      - "MYSQL_PASSWORD=jiehdo!25165n"
    restart: always
  
  app:
    image: kodcloud/kodbox
    ports:
      - 8080:80                
    links:
      - db
      - redis
    volumes:
      - "/project/sandbox/site:/var/www/html"  
    restart: always

  redis:
    image: redis:alpine
    environment:
      - "TZ=Asia/Shanghai"
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    command: tunnel --edge-ip-version auto --protocol quic --heartbeat-interval 10s run --token $CF_ZERO_TRUST_TOKEN

networks:
  halo_network:
